services:
  - type: web
    name: suvtekin-auto
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        fromDatabase:
          name: suvtekin-db
          property: connectionString